### ISSUE TITLE
Error when running roslaunch vision_to_mavros t265_tf_to_mavros.launch

### ISSUE THREAD

**Issue by Wina30** [thien94/vision_to_mavros#50]
I get warning on my terminal, that say "[ WARN] [1636146132.931182478]: "camera_odom_frame" passed to lookupTransform argument target_frame does not exist. ", that make problem with my drone because when I opened the inspector mavlink, that say is no viso_estimate was connect on my pixhawk.
![image](https://user-images.githubusercontent.com/58365279/140578890-6f8c829a-bff0-45f5-a3bd-d6ef6f1a1f66.png)

**Comment by thien94** [comment]
As the error message says, the issue is that there is no `camera_odom_frame` in the `/tf` tree. Either the camera driver is not running, or the name of the frame(s) does not match.

First, check the camera driver launch file, verify that it is working properly and verify the names of the frame ids.
If the driver is running ok, either modify the frame id on the driver's side or in the `t265_tf_to_mavros.launch` file.

Hope this helps.

**Comment by Wina30** [comment]
in my rostopic echo /tf doesn't appear any information 
![image](https://user-images.githubusercontent.com/58365279/140608146-5e370f3b-4603-4472-8f15-5f7cfbd76dd1.png)
so is my problem relate to the camera driver?

**Comment by thien94** [comment]
Yes, that seems to be the case. If the driver is running properly, the `/tf` should be populated.

**Comment by Wina30** [comment]
Thanks about your answer, my realsense was work now, I just reinstall my realsense driver
