### ISSUE TITLE
using d415 instead of t265 

### ISSUE THREAD

**Issue by deepak98066** [thien94/vision_to_mavros#59]
hello,
I am trying to setup obstacle avoidance on my drone using realsense D415 depth camera (https://ardupilot.org/copter/docs/common-realsense-depth-camera.html#manually-setup-the-companion-computer ) 
can you please share the required steps i need to take care for this?

**Comment by thien94** [comment]
Hi @deepak98066 , sorry for the late reply.

Since the D415 does not have an IMU and does not provide odometry data out of the box, I would not recommend using it. Unless you are already quite familiar with SLAM + ROS + ArduPilot/PX4, the steps to use this sensor are not really simple and straightforward.
